platform :ios, '9.0'

target 'iOSApp' do
   pod 'Masonry'
   flutter_application_path = '../flutter_player_module'
   eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
